// Code generated by MockGen. DO NOT EDIT.
// Source: chrome_driver.go
//
// Generated by this command:
//
//	mockgen -source=chrome_driver.go -destination=../mocks/chrome_driver_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dariomba/screen-go/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockChromeDriver is a mock of ChromeDriver interface.
type MockChromeDriver struct {
	ctrl     *gomock.Controller
	recorder *MockChromeDriverMockRecorder
	isgomock struct{}
}

// MockChromeDriverMockRecorder is the mock recorder for MockChromeDriver.
type MockChromeDriverMockRecorder struct {
	mock *MockChromeDriver
}

// NewMockChromeDriver creates a new mock instance.
func NewMockChromeDriver(ctrl *gomock.Controller) *MockChromeDriver {
	mock := &MockChromeDriver{ctrl: ctrl}
	mock.recorder = &MockChromeDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChromeDriver) EXPECT() *MockChromeDriverMockRecorder {
	return m.recorder
}

// CaptureScreenshot mocks base method.
func (m *MockChromeDriver) CaptureScreenshot(ctx context.Context, job *domain.Job) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CaptureScreenshot", ctx, job)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CaptureScreenshot indicates an expected call of CaptureScreenshot.
func (mr *MockChromeDriverMockRecorder) CaptureScreenshot(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CaptureScreenshot", reflect.TypeOf((*MockChromeDriver)(nil).CaptureScreenshot), ctx, job)
}

// Shutdown mocks base method.
func (m *MockChromeDriver) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockChromeDriverMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockChromeDriver)(nil).Shutdown), ctx)
}
