// Code generated by MockGen. DO NOT EDIT.
// Source: job_repository.go
//
// Generated by this command:
//
//	mockgen -source=job_repository.go -destination=../mocks/job_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dariomba/screen-go/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockJobRepository is a mock of JobRepository interface.
type MockJobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobRepositoryMockRecorder
	isgomock struct{}
}

// MockJobRepositoryMockRecorder is the mock recorder for MockJobRepository.
type MockJobRepositoryMockRecorder struct {
	mock *MockJobRepository
}

// NewMockJobRepository creates a new mock instance.
func NewMockJobRepository(ctrl *gomock.Controller) *MockJobRepository {
	mock := &MockJobRepository{ctrl: ctrl}
	mock.recorder = &MockJobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobRepository) EXPECT() *MockJobRepositoryMockRecorder {
	return m.recorder
}

// CreateJob mocks base method.
func (m *MockJobRepository) CreateJob(ctx context.Context, job *domain.Job) (*domain.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", ctx, job)
	ret0, _ := ret[0].(*domain.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockJobRepositoryMockRecorder) CreateJob(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockJobRepository)(nil).CreateJob), ctx, job)
}

// GetJobByID mocks base method.
func (m *MockJobRepository) GetJobByID(ctx context.Context, jobID string) (*domain.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobByID", ctx, jobID)
	ret0, _ := ret[0].(*domain.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobByID indicates an expected call of GetJobByID.
func (mr *MockJobRepositoryMockRecorder) GetJobByID(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobByID", reflect.TypeOf((*MockJobRepository)(nil).GetJobByID), ctx, jobID)
}

// UpdateJobToCompleted mocks base method.
func (m *MockJobRepository) UpdateJobToCompleted(ctx context.Context, jobID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobToCompleted", ctx, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJobToCompleted indicates an expected call of UpdateJobToCompleted.
func (mr *MockJobRepositoryMockRecorder) UpdateJobToCompleted(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobToCompleted", reflect.TypeOf((*MockJobRepository)(nil).UpdateJobToCompleted), ctx, jobID)
}

// UpdateJobToFailed mocks base method.
func (m *MockJobRepository) UpdateJobToFailed(ctx context.Context, jobID, errorMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobToFailed", ctx, jobID, errorMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJobToFailed indicates an expected call of UpdateJobToFailed.
func (mr *MockJobRepositoryMockRecorder) UpdateJobToFailed(ctx, jobID, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobToFailed", reflect.TypeOf((*MockJobRepository)(nil).UpdateJobToFailed), ctx, jobID, errorMessage)
}

// UpdateJobToProcessing mocks base method.
func (m *MockJobRepository) UpdateJobToProcessing(ctx context.Context, jobID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobToProcessing", ctx, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJobToProcessing indicates an expected call of UpdateJobToProcessing.
func (mr *MockJobRepositoryMockRecorder) UpdateJobToProcessing(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobToProcessing", reflect.TypeOf((*MockJobRepository)(nil).UpdateJobToProcessing), ctx, jobID)
}
