// Code generated by MockGen. DO NOT EDIT.
// Source: job_processor.go
//
// Generated by this command:
//
//	mockgen -source=job_processor.go -destination=../mocks/job_processor_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dariomba/screen-go/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockJobProcessor is a mock of JobProcessor interface.
type MockJobProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockJobProcessorMockRecorder
	isgomock struct{}
}

// MockJobProcessorMockRecorder is the mock recorder for MockJobProcessor.
type MockJobProcessorMockRecorder struct {
	mock *MockJobProcessor
}

// NewMockJobProcessor creates a new mock instance.
func NewMockJobProcessor(ctrl *gomock.Controller) *MockJobProcessor {
	mock := &MockJobProcessor{ctrl: ctrl}
	mock.recorder = &MockJobProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobProcessor) EXPECT() *MockJobProcessorMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockJobProcessor) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockJobProcessorMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockJobProcessor)(nil).Close))
}

// Process mocks base method.
func (m *MockJobProcessor) Process(ctx context.Context, job *domain.Job) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Process", ctx, job)
}

// Process indicates an expected call of Process.
func (mr *MockJobProcessorMockRecorder) Process(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockJobProcessor)(nil).Process), ctx, job)
}
