// Code generated by MockGen. DO NOT EDIT.
// Source: screenshot_repository.go
//
// Generated by this command:
//
//	mockgen -source=screenshot_repository.go -destination=../mocks/screenshot_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dariomba/screen-go/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockScreenshotRepository is a mock of ScreenshotRepository interface.
type MockScreenshotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScreenshotRepositoryMockRecorder
	isgomock struct{}
}

// MockScreenshotRepositoryMockRecorder is the mock recorder for MockScreenshotRepository.
type MockScreenshotRepositoryMockRecorder struct {
	mock *MockScreenshotRepository
}

// NewMockScreenshotRepository creates a new mock instance.
func NewMockScreenshotRepository(ctrl *gomock.Controller) *MockScreenshotRepository {
	mock := &MockScreenshotRepository{ctrl: ctrl}
	mock.recorder = &MockScreenshotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScreenshotRepository) EXPECT() *MockScreenshotRepositoryMockRecorder {
	return m.recorder
}

// CreateScreenshot mocks base method.
func (m *MockScreenshotRepository) CreateScreenshot(ctx context.Context, screenshot *domain.Screenshot) (*domain.Screenshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScreenshot", ctx, screenshot)
	ret0, _ := ret[0].(*domain.Screenshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScreenshot indicates an expected call of CreateScreenshot.
func (mr *MockScreenshotRepositoryMockRecorder) CreateScreenshot(ctx, screenshot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScreenshot", reflect.TypeOf((*MockScreenshotRepository)(nil).CreateScreenshot), ctx, screenshot)
}

// GetScreenshotByJobID mocks base method.
func (m *MockScreenshotRepository) GetScreenshotByJobID(ctx context.Context, jobID string) (*domain.Screenshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScreenshotByJobID", ctx, jobID)
	ret0, _ := ret[0].(*domain.Screenshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScreenshotByJobID indicates an expected call of GetScreenshotByJobID.
func (mr *MockScreenshotRepositoryMockRecorder) GetScreenshotByJobID(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScreenshotByJobID", reflect.TypeOf((*MockScreenshotRepository)(nil).GetScreenshotByJobID), ctx, jobID)
}
