// Code generated by MockGen. DO NOT EDIT.
// Source: screenshot_storage.go
//
// Generated by this command:
//
//	mockgen -source=screenshot_storage.go -destination=../mocks/screenshot_storage_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	ports "github.com/dariomba/screen-go/internal/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockScreenshotStorage is a mock of ScreenshotStorage interface.
type MockScreenshotStorage struct {
	ctrl     *gomock.Controller
	recorder *MockScreenshotStorageMockRecorder
	isgomock struct{}
}

// MockScreenshotStorageMockRecorder is the mock recorder for MockScreenshotStorage.
type MockScreenshotStorageMockRecorder struct {
	mock *MockScreenshotStorage
}

// NewMockScreenshotStorage creates a new mock instance.
func NewMockScreenshotStorage(ctrl *gomock.Controller) *MockScreenshotStorage {
	mock := &MockScreenshotStorage{ctrl: ctrl}
	mock.recorder = &MockScreenshotStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScreenshotStorage) EXPECT() *MockScreenshotStorageMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockScreenshotStorage) Get(ctx context.Context, key string) (io.Reader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(io.Reader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockScreenshotStorageMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockScreenshotStorage)(nil).Get), ctx, key)
}

// Save mocks base method.
func (m *MockScreenshotStorage) Save(ctx context.Context, input *ports.SaveScreenshotInput) (*ports.SaveScreenshotResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, input)
	ret0, _ := ret[0].(*ports.SaveScreenshotResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockScreenshotStorageMockRecorder) Save(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockScreenshotStorage)(nil).Save), ctx, input)
}
