// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    id,
    url,
    format,
    width,
    height,
    full_page,
    status
) VALUES (
    $1,
    $2,
    COALESCE($3::job_format, 'png'),
    COALESCE($4::integer, 1280),
    COALESCE($5::integer, 800),
    COALESCE($6::boolean, false),
    'pending'
)
RETURNING id, url, format, width, height, full_page, status, error, started_at, finished_at, created_at, updated_at
`

type CreateJobParams struct {
	ID       string
	Url      string
	Format   NullJobFormat
	Width    pgtype.Int4
	Height   pgtype.Int4
	FullPage pgtype.Bool
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.Url,
		arg.Format,
		arg.Width,
		arg.Height,
		arg.FullPage,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Format,
		&i.Width,
		&i.Height,
		&i.FullPage,
		&i.Status,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobToDone = `-- name: UpdateJobToDone :exec
UPDATE jobs
SET 
    status = 'done',
    finished_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND status = 'processing'
`

func (q *Queries) UpdateJobToDone(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateJobToDone, id)
	return err
}

const updateJobToFailed = `-- name: UpdateJobToFailed :exec
UPDATE jobs
SET 
    status = 'failed',
    finished_at = NOW(),
    error = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateJobToFailedParams struct {
	ID    string
	Error pgtype.Text
}

func (q *Queries) UpdateJobToFailed(ctx context.Context, arg UpdateJobToFailedParams) error {
	_, err := q.db.Exec(ctx, updateJobToFailed, arg.ID, arg.Error)
	return err
}

const updateJobToProcessing = `-- name: UpdateJobToProcessing :exec
UPDATE jobs
SET 
    status = 'processing',
    started_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND status = 'pending'
`

func (q *Queries) UpdateJobToProcessing(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateJobToProcessing, id)
	return err
}
