// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: screenshots.sql

package sqlc

import (
	"context"
)

const createScreenshot = `-- name: CreateScreenshot :one
INSERT INTO screenshots (
    id,
    job_id,
    storage_key,
    content_type,
    size_bytes
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, job_id, storage_key, content_type, size_bytes, created_at
`

type CreateScreenshotParams struct {
	ID          string
	JobID       string
	StorageKey  string
	ContentType string
	SizeBytes   int64
}

func (q *Queries) CreateScreenshot(ctx context.Context, arg CreateScreenshotParams) (Screenshot, error) {
	row := q.db.QueryRow(ctx, createScreenshot,
		arg.ID,
		arg.JobID,
		arg.StorageKey,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i Screenshot
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getScreenshotByJobID = `-- name: GetScreenshotByJobID :one
SELECT id, job_id, storage_key, content_type, size_bytes, created_at FROM screenshots
WHERE job_id = $1
`

func (q *Queries) GetScreenshotByJobID(ctx context.Context, jobID string) (Screenshot, error) {
	row := q.db.QueryRow(ctx, getScreenshotByJobID, jobID)
	var i Screenshot
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}
