//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for CreateJobRequestFormat.
const (
	CreateJobRequestFormatPdf CreateJobRequestFormat = "pdf"
	CreateJobRequestFormatPng CreateJobRequestFormat = "png"
)

// Defines values for CreateJobResponseStatus.
const (
	CreateJobResponseStatusPending CreateJobResponseStatus = "pending"
)

// Defines values for JobFormat.
const (
	JobFormatPdf JobFormat = "pdf"
	JobFormatPng JobFormat = "png"
)

// Defines values for JobStatus.
const (
	JobStatusDone       JobStatus = "done"
	JobStatusFailed     JobStatus = "failed"
	JobStatusPending    JobStatus = "pending"
	JobStatusProcessing JobStatus = "processing"
)

// CreateJobRequest defines model for CreateJobRequest.
type CreateJobRequest struct {
	// Format Output format. PDFs capture the full page regardless of `full_page`.
	Format *CreateJobRequestFormat `json:"format,omitempty"`

	// FullPage Capture the full scrollable page height instead of just the viewport.
	// Increases memory usage proportionally to page length.
	FullPage *bool `json:"full_page,omitempty"`

	// Height Viewport height in pixels.
	Height *int `json:"height,omitempty"`

	// URL The URL to screenshot. Must be a reachable http or https URL.
	URL string `json:"url"`

	// Width Viewport width in pixels.
	Width *int `json:"width,omitempty"`
}

// CreateJobRequestFormat Output format. PDFs capture the full page regardless of `full_page`.
type CreateJobRequestFormat string

// CreateJobResponse defines model for CreateJobResponse.
type CreateJobResponse struct {
	// JobID Unique ID identifier for the job.
	JobID string `json:"job_id"`

	// Status Initial status is always `pending`.
	Status CreateJobResponseStatus `json:"status"`

	// StatusURL Convenience URL to poll for job status.
	StatusURL string `json:"status_url"`
}

// CreateJobResponseStatus Initial status is always `pending`.
type CreateJobResponseStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Human-readable description of what went wrong.
	Error string `json:"error"`
}

// Job defines model for Job.
type Job struct {
	// DurationMs Total processing time in milliseconds. Null until finished.
	DurationMs *int `json:"duration_ms,omitempty"`

	// Error Human-readable error message. Only present when status is `failed`.
	Error *string `json:"error,omitempty"`

	// FinishedAt When the job finished (success or failure). Null while pending or processing.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	Format     JobFormat  `json:"format"`
	FullPage   bool       `json:"full_page"`
	Height     int        `json:"height"`
	JobID      string     `json:"job_id"`

	// MemoryUsedMb Actual memory used, recorded after the job completes. Null until done.
	MemoryUsedMb *int `json:"memory_used_mb,omitempty"`

	// ScreenshotURL URL to fetch the screenshot file. Only present when status is `done`.
	ScreenshotURL *string `json:"screenshot_url,omitempty"`

	// StartedAt When the job started processing. Null while still pending.
	StartedAt *time.Time `json:"started_at,omitempty"`

	// Status - `pending` — waiting for available pod memory
	// - `processing` — Chrome is actively rendering the page
	// - `done` — screenshot is ready to download
	// - `failed` — job encountered an unrecoverable error
	Status JobStatus `json:"status"`
	URL    string    `json:"url"`
	Width  int       `json:"width"`
}

// JobFormat defines model for Job.Format.
type JobFormat string

// JobStatus - `pending` — waiting for available pod memory
// - `processing` — Chrome is actively rendering the page
// - `done` — screenshot is ready to download
// - `failed` — job encountered an unrecoverable error
type JobStatus string

// JobID defines model for JobId.
type JobID = string

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = CreateJobRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Submit a screenshot job
	// (POST /v1/job)
	CreateJob(w http.ResponseWriter, r *http.Request)
	// Get job status
	// (GET /v1/job/{id})
	GetJobStatus(w http.ResponseWriter, r *http.Request, id JobID)
	// Download screenshot file
	// (GET /v1/screenshot/{id})
	GetScreenshot(w http.ResponseWriter, r *http.Request, id JobID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateJob operation middleware
func (siw *ServerInterfaceWrapper) CreateJob(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJobStatus operation middleware
func (siw *ServerInterfaceWrapper) GetJobStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJobStatus(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetScreenshot operation middleware
func (siw *ServerInterfaceWrapper) GetScreenshot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetScreenshot(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/v1/job", wrapper.CreateJob)
	m.HandleFunc("GET "+options.BaseURL+"/v1/job/{id}", wrapper.GetJobStatus)
	m.HandleFunc("GET "+options.BaseURL+"/v1/screenshot/{id}", wrapper.GetScreenshot)

	return m
}

type CreateJobRequestObject struct {
	Body *CreateJobJSONRequestBody
}

type CreateJobResponseObject interface {
	VisitCreateJobResponse(w http.ResponseWriter) error
}

type CreateJob202JSONResponse CreateJobResponse

func (response CreateJob202JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob400JSONResponse ErrorResponse

func (response CreateJob400JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob413JSONResponse ErrorResponse

func (response CreateJob413JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob422JSONResponse ErrorResponse

func (response CreateJob422JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob500JSONResponse ErrorResponse

func (response CreateJob500JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetJobStatusRequestObject struct {
	ID JobID `json:"id"`
}

type GetJobStatusResponseObject interface {
	VisitGetJobStatusResponse(w http.ResponseWriter) error
}

type GetJobStatus200JSONResponse Job

func (response GetJobStatus200JSONResponse) VisitGetJobStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetJobStatus404JSONResponse ErrorResponse

func (response GetJobStatus404JSONResponse) VisitGetJobStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetJobStatus500JSONResponse ErrorResponse

func (response GetJobStatus500JSONResponse) VisitGetJobStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetScreenshotRequestObject struct {
	ID JobID `json:"id"`
}

type GetScreenshotResponseObject interface {
	VisitGetScreenshotResponse(w http.ResponseWriter) error
}

type GetScreenshot200ResponseHeaders struct {
	ContentDisposition string
	ContentLength      int
	ContentType        string
}

type GetScreenshot200ApplicationPdfResponse struct {
	Body          io.Reader
	Headers       GetScreenshot200ResponseHeaders
	ContentLength int64
}

func (response GetScreenshot200ApplicationPdfResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/pdf")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.Header().Set("Content-Type", fmt.Sprint(response.Headers.ContentType))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetScreenshot200ImagePngResponse struct {
	Body          io.Reader
	Headers       GetScreenshot200ResponseHeaders
	ContentLength int64
}

func (response GetScreenshot200ImagePngResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "image/png")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.Header().Set("Content-Type", fmt.Sprint(response.Headers.ContentType))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetScreenshot404JSONResponse ErrorResponse

func (response GetScreenshot404JSONResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetScreenshot500JSONResponse ErrorResponse

func (response GetScreenshot500JSONResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Submit a screenshot job
	// (POST /v1/job)
	CreateJob(ctx context.Context, request CreateJobRequestObject) (CreateJobResponseObject, error)
	// Get job status
	// (GET /v1/job/{id})
	GetJobStatus(ctx context.Context, request GetJobStatusRequestObject) (GetJobStatusResponseObject, error)
	// Download screenshot file
	// (GET /v1/screenshot/{id})
	GetScreenshot(ctx context.Context, request GetScreenshotRequestObject) (GetScreenshotResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateJob operation middleware
func (sh *strictHandler) CreateJob(w http.ResponseWriter, r *http.Request) {
	var request CreateJobRequestObject

	var body CreateJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateJob(ctx, request.(CreateJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateJobResponseObject); ok {
		if err := validResponse.VisitCreateJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJobStatus operation middleware
func (sh *strictHandler) GetJobStatus(w http.ResponseWriter, r *http.Request, id JobID) {
	var request GetJobStatusRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJobStatus(ctx, request.(GetJobStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJobStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobStatusResponseObject); ok {
		if err := validResponse.VisitGetJobStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetScreenshot operation middleware
func (sh *strictHandler) GetScreenshot(w http.ResponseWriter, r *http.Request, id JobID) {
	var request GetScreenshotRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetScreenshot(ctx, request.(GetScreenshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetScreenshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetScreenshotResponseObject); ok {
		if err := validResponse.VisitGetScreenshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+Raf2/jthn+KoS2P1rAsRXb13M97I/2cndLdr92Sdvt6iCmxNcWU4rUkZQdrwiwD7FP",
	"uE8yvKQsUbbcc9JbUWBAgV4kinx/8Xme901+jlKVF0qCtCaa/hwVVNMcLGj304VKzhn+g4FJNS8sVzKa",
	"Rudn5FYlhDOQli84aKLBlloCI8mGzN+9vbwig9Xp4FYl86gXcfymoDaLepGkOUTTiLOoF2n4WHINLJpa",
	"XUIvMmkGOcXj4I7mhYBo+mMUn16M//rhb3+fvBy9Gb57+vrJ+6+v4u9/+Mfzr6LrXmQ3BW5nrOZyGd3f",
	"3293ceY/00AtXKjkPXwswVjnoFYFaMvBrVgonVPrPVzQUli0VC6j3o7Hb0tblJb45X3y7uyFISktbKmB",
	"2AzIohSCFHQJRMOSaibAGKIWZI4vbvDFvB/1IpBljk75Iwq26PChF9XftOxaUGFg165nuzaYVCshaCLA",
	"m5MBX2aWcGksUIYm3ZbGuvUrDutCadufyXOZaqAGDMkhV3pDSoMfY6yUxqOoEBtild9TgFzarD+TUW18",
	"opQAKtF6f2LL9Ekc7xr+fXV4YyAp+B0Ig2HK6R3PMVLD06/iXpRzWf04jusTubSwBI0nllrs1+hVBuS7",
	"96/QaJNqAGkyZfvkNXqfAKFEA00zF6jM2oIo7f5v8COXqqYE3fPpYLDkNiuTfqpyTNu2dKJS86gji2vO",
	"bNYKw+lwcjgObvmBMIwm4zAMo2FHGO7D+/Sji0lTWyq5hdSiVcGVMIWSBvbvxK1KbnjHrf9O8o8lkPOz",
	"8OIvlHbFdKuSnag96OL2ImOpLU0H1khuORXEvyfcECrWdGPIvADJuFy2L5Z/9gsn3HRWyzMlVyA5yLSu",
	"mkIJ4dxDqPPf7nhYQdzgYRDVzlMV7Nr/lpldCXyutdKHkwf4et+/v5Q5lScaKHMVH7xESFhn1JI1SEvW",
	"WsnljpulhLsCUguMuN2JStNSo/2f9M5b0+XGhUr2jWelpmjTTd5RCFfKUoGQlIIxXC6J5Tnghcm5ENxA",
	"qiQzffIGUbCUlguy4JKbDFjbnyenw/i6C0aOC50PQQ4GEbJP3kqxIYUG46KXgQwKdb6gXACb78QzVdLC",
	"nSUMKBNcAoG7FIABm3p4ZZwRqSwRijKy5jbjkoxi000VlYs3WxILLf8BzakuZx0M8oUp09TRkyZoYKnh",
	"yyps64wjb/g7hO+baKMPNeIxauEEw9+Few2lPoLtmjA5urv+ZYJpVk/i7pw2WPZ4ZPKUeFMaYDd5sh/m",
	"b1JbUtEwJ7Ae0ZAqzYARurBQIyRBrSXAQrtOmZLQrpHh5GmnOw2TdcNYBV0LsGnmDm0+IAsuPlWvaMhu",
	"tQ6aLQYPh3Rtj6nNamFYbmFBGstRXfmyPL4QG0b5o4ZFNI3+MGi07qCSiYMLlVz6hY2S+Hzc3+yE5H/9",
	"Sdqu6QAtqc/ZbljXfnhrAupIHbm7gB/A3MsDLHvS0Cn5z7/+TdaUW8QA5D+6orxSlIpVZT6T+EWdLv/R",
	"s0wrhGRDaGr5CsSGaJAMtEPrzCtS96UrNPdNUKDcoCZjTmcytZaIf251BaNuPZYLyFSV0oLG+yVJKfG2",
	"rUA3+Oyk6a4m6EWNwSjwlcTg+c0P9BJcLtR+sC5BLE4yZbBkG/tPqDmhJwb0iqfQn8mZ/IYIzNbaK9yc",
	"p1pVr4lFxrX0JzBkDYnhNryqhqw4JRnSA+K0D2uPUMmIhBVo8vbta0O4NSAW2HBZTdOfMMYVBBWgqwyQ",
	"RKu1Ae30P5XOrqgXCZ5CpR6qfuz1+RVWiOUWizW6dLa8VFEvWoE23u24f9qPcZUqQNKCR9No1I/7MQaW",
	"2sxVVSWJHLUrY7vAMoXCGkLDzGvfnjkPeZ4D49T66sGuEhdj2s/P+jN5VUEGN+RjCaWrAGRJIVDVVwkG",
	"5qENpCqXWatssTi39dwn71DjzV8+r9vVwc+c3c+xAl1QccOlBmN83FCrOIGCTXEjpatWFoz9VrEN+uwo",
	"Xjr3aVEInrqvBrcGY1CjgotYQg1P8R+mzHOqN9E0+hYfBfHBLFBRQtiwVqS65ULXYTn06kKsGpAQhO5D",
	"zr1BVm4d/qLuZN+dveg+mS1aAFR171tTvt43RcLa9DepyhMuqVV6x6jxOA46908B9l5Tf98GUbTGPfAS",
	"2QV5GA+PT0vYA/2SVmgYJoCYsMk4pkF4jNuV9nd+t2/XhUoIdTesuhj+juAp4zh+WAgqORxxuaKCM1Jq",
	"MSV53T77h3ut8/EOtRuZDmfOq4O36JAotsGzSmnKAntmYNsTx6ejxzkHxvIcOXOLnV+cTuI4T76sRLkh",
	"1rUdScmWYMkXT7+a5MmXn9FJxLPKQWD1SIYY/k9oTEAhVxFHZWZlD7bhGsTGASM3lcYsxZYodCl3BlKu",
	"c5O+uUBQw+ANh48Lnh9ZbEsiAbsGkGQ0jF3pjSbj+DMG6n1YBdxU9Xdx+fYNSUrrOhlDDORUWp76t84B",
	"NOHJUbX/mQz9rmmXMWmgvSRxUq+B2csyyblt0+CtoxJLlwZly4VKTHSNX4XchOYtoYNY31dcicWyTTKC",
	"EWDWHYFWdGexUECyQnFpfQcyk3OPW3OMLHCbgd6KNKWbPhZFjRPu4XK/rkcombfbkzlZcBAM13CZipIB",
	"m0l3qtODqiHeoMVw/NvFti/BNvq115pT/9idsWbJwM+x76/3aCF+IFs70djiy4ugrWOk6q2RHDcheQbK",
	"fIpsND6JT09On1ydxtMY//uAgjScfjw5Hcb1SEKWQuz0+h2bTD6ErZHXBwFLV/PjlmI4juZ2G+Dh5Ol+",
	"K3pso9huCzvcGH0ImbVS6Q+QNl7P7+Woev5rcjKK47hJyqPnOJ/M5Gj0W2XSF9ZuKqunD0lTHd3jE7XV",
	"THuZCntPb/Cvypr35vBNqh79jqJdP9kVlw8IbtPp7qOVZwfsr0op/c7/T+H9ZDG3xgTHxvxopYMN4wHp",
	"vlClZG7MkWaQ/tTQrCdSvBAtave6fvw49YZaEeHJHfoZhdob5efNzheEPSdJlnwFkpyf/U7l2Euwwe95",
	"DqqwHaFyUIxdWg0092JM0/XuGNaP1QLZgOrMzzbmz3xUTq42BczdEAh0Pd+Y85wuYVDIpRdmYdwKtpjP",
	"JIN6fO/nq/7mBT3GOpy8rqkh1ZV36m6rIsfxmPBFvYwpMK5Y4I4b2yMZ9T82HmzA9mZS6e1Xgce4OMHO",
	"gIFfy0pA+Xd19YrAXcH15oDeuwwnIL+B4NvOQurCq1Er4ZI6Gtr/dVedkYd+uleplztFYlwRuSEPFoH/",
	"i4aqOs64KZTh/su96iuXS59r3EfS3BfcdqYazvcjai1Nsxyk/VO9+s+zyEhauKHmYQTuF3I5i6IQN/aj",
	"s7X3lfuTgX1TXzhHsdnlkiQbC6Zrw3BaHt6P/f1en79+TvAr7HraddjaeDsbbrLX2yuFrpHwrwHc4Er8",
	"L3D3smP7emSe0014f/FH/1uVZmjK5bKHoILXEt9ndAX+fvoB0u8Qtc+qit7F1wC/m6g4GMfP3X4eRdqH",
	"vlIpFYTBCoQq8Eq06H86GAhckCljp5N4Ejt4qc7Zv4K+vZeMcGnQk51G3zR/C+Uo5r7X0dBrDqtwqL3j",
	"ZrBH6Ob99f1/AwAA//9iUls51iUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
