//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for CreateJobRequestFormat.
const (
	CreateJobRequestFormatPdf CreateJobRequestFormat = "pdf"
	CreateJobRequestFormatPng CreateJobRequestFormat = "png"
)

// Defines values for CreateJobResponseStatus.
const (
	CreateJobResponseStatusQueued CreateJobResponseStatus = "queued"
)

// Defines values for JobFormat.
const (
	JobFormatPdf JobFormat = "pdf"
	JobFormatPng JobFormat = "png"
)

// Defines values for JobStatus.
const (
	JobStatusDone       JobStatus = "done"
	JobStatusFailed     JobStatus = "failed"
	JobStatusProcessing JobStatus = "processing"
	JobStatusQueued     JobStatus = "queued"
)

// CreateJobRequest defines model for CreateJobRequest.
type CreateJobRequest struct {
	// Format Output format. PDFs capture the full page regardless of `full_page`.
	Format *CreateJobRequestFormat `json:"format,omitempty"`

	// FullPage Capture the full scrollable page height instead of just the viewport.
	// Increases memory usage proportionally to page length.
	FullPage *bool `json:"full_page,omitempty"`

	// Height Viewport height in pixels.
	Height *int `json:"height,omitempty"`

	// URL The URL to screenshot. Must be a reachable http or https URL.
	URL string `json:"url"`

	// Width Viewport width in pixels.
	Width *int `json:"width,omitempty"`
}

// CreateJobRequestFormat Output format. PDFs capture the full page regardless of `full_page`.
type CreateJobRequestFormat string

// CreateJobResponse defines model for CreateJobResponse.
type CreateJobResponse struct {
	// EstimatedMemoryMb Estimated memory this job will reserve from the pod budget
	// while processing. Informational only.
	EstimatedMemoryMb int `json:"estimated_memory_mb"`

	// JobID Unique ID identifier for the job.
	JobID string `json:"job_id"`

	// Status Initial status is always `queued`.
	Status CreateJobResponseStatus `json:"status"`

	// StatusURL Convenience URL to poll for job status.
	StatusURL string `json:"status_url"`
}

// CreateJobResponseStatus Initial status is always `queued`.
type CreateJobResponseStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Human-readable description of what went wrong.
	Error string `json:"error"`
}

// Job defines model for Job.
type Job struct {
	// DurationMs Total processing time in milliseconds. Null until finished.
	DurationMs *int `json:"duration_ms,omitempty"`

	// Error Human-readable error message. Only present when status is `failed`.
	Error *string `json:"error,omitempty"`

	// EstimatedMemoryMb Memory reserved from the pod budget for this job.
	EstimatedMemoryMb int `json:"estimated_memory_mb"`

	// FinishedAt When the job finished (success or failure). Null while pending or processing.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	Format     JobFormat  `json:"format"`
	FullPage   bool       `json:"full_page"`
	Height     int        `json:"height"`
	JobID      string     `json:"job_id"`

	// MemoryUsedMb Actual memory used, recorded after the job completes. Null until done.
	MemoryUsedMb *int `json:"memory_used_mb,omitempty"`

	// QueuedAt When the job was accepted by the service.
	QueuedAt time.Time `json:"queued_at"`

	// ScreenshotURL URL to fetch the screenshot file. Only present when status is `done`.
	ScreenshotURL *string `json:"screenshot_url,omitempty"`

	// StartedAt When the job started processing. Null while still queued.
	StartedAt *time.Time `json:"started_at,omitempty"`

	// Status - `queued` — waiting for available pod memory
	// - `processing` — Chrome is actively rendering the page
	// - `done` — screenshot is ready to download
	// - `failed` — job encountered an unrecoverable error
	Status JobStatus `json:"status"`
	URL    string    `json:"url"`
	Width  int       `json:"width"`
}

// JobFormat defines model for Job.Format.
type JobFormat string

// JobStatus - `queued` — waiting for available pod memory
// - `processing` — Chrome is actively rendering the page
// - `done` — screenshot is ready to download
// - `failed` — job encountered an unrecoverable error
type JobStatus string

// JobID defines model for JobId.
type JobID = string

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = CreateJobRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Submit a screenshot job
	// (POST /job)
	CreateJob(w http.ResponseWriter, r *http.Request)
	// Get job status
	// (GET /job/{id})
	GetJob(w http.ResponseWriter, r *http.Request, id JobID)
	// Download screenshot file
	// (GET /screenshot/{id})
	GetScreenshot(w http.ResponseWriter, r *http.Request, id JobID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateJob operation middleware
func (siw *ServerInterfaceWrapper) CreateJob(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJob operation middleware
func (siw *ServerInterfaceWrapper) GetJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetScreenshot operation middleware
func (siw *ServerInterfaceWrapper) GetScreenshot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetScreenshot(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/job", wrapper.CreateJob)
	m.HandleFunc("GET "+options.BaseURL+"/job/{id}", wrapper.GetJob)
	m.HandleFunc("GET "+options.BaseURL+"/screenshot/{id}", wrapper.GetScreenshot)

	return m
}

type CreateJobRequestObject struct {
	Body *CreateJobJSONRequestBody
}

type CreateJobResponseObject interface {
	VisitCreateJobResponse(w http.ResponseWriter) error
}

type CreateJob202JSONResponse CreateJobResponse

func (response CreateJob202JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob400JSONResponse ErrorResponse

func (response CreateJob400JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob413JSONResponse ErrorResponse

func (response CreateJob413JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob422JSONResponse ErrorResponse

func (response CreateJob422JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob500JSONResponse ErrorResponse

func (response CreateJob500JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetJobRequestObject struct {
	ID JobID `json:"id"`
}

type GetJobResponseObject interface {
	VisitGetJobResponse(w http.ResponseWriter) error
}

type GetJob200JSONResponse Job

func (response GetJob200JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetJob404JSONResponse ErrorResponse

func (response GetJob404JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetJob500JSONResponse ErrorResponse

func (response GetJob500JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetScreenshotRequestObject struct {
	ID JobID `json:"id"`
}

type GetScreenshotResponseObject interface {
	VisitGetScreenshotResponse(w http.ResponseWriter) error
}

type GetScreenshot200ResponseHeaders struct {
	ContentDisposition string
	ContentLength      int
	ContentType        string
}

type GetScreenshot200ApplicationPdfResponse struct {
	Body          io.Reader
	Headers       GetScreenshot200ResponseHeaders
	ContentLength int64
}

func (response GetScreenshot200ApplicationPdfResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/pdf")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.Header().Set("Content-Type", fmt.Sprint(response.Headers.ContentType))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetScreenshot200ImagePngResponse struct {
	Body          io.Reader
	Headers       GetScreenshot200ResponseHeaders
	ContentLength int64
}

func (response GetScreenshot200ImagePngResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "image/png")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.Header().Set("Content-Type", fmt.Sprint(response.Headers.ContentType))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetScreenshot404JSONResponse ErrorResponse

func (response GetScreenshot404JSONResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetScreenshot500JSONResponse ErrorResponse

func (response GetScreenshot500JSONResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Submit a screenshot job
	// (POST /job)
	CreateJob(ctx context.Context, request CreateJobRequestObject) (CreateJobResponseObject, error)
	// Get job status
	// (GET /job/{id})
	GetJob(ctx context.Context, request GetJobRequestObject) (GetJobResponseObject, error)
	// Download screenshot file
	// (GET /screenshot/{id})
	GetScreenshot(ctx context.Context, request GetScreenshotRequestObject) (GetScreenshotResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateJob operation middleware
func (sh *strictHandler) CreateJob(w http.ResponseWriter, r *http.Request) {
	var request CreateJobRequestObject

	var body CreateJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateJob(ctx, request.(CreateJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateJobResponseObject); ok {
		if err := validResponse.VisitCreateJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJob operation middleware
func (sh *strictHandler) GetJob(w http.ResponseWriter, r *http.Request, id JobID) {
	var request GetJobRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJob(ctx, request.(GetJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobResponseObject); ok {
		if err := validResponse.VisitGetJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetScreenshot operation middleware
func (sh *strictHandler) GetScreenshot(w http.ResponseWriter, r *http.Request, id JobID) {
	var request GetScreenshotRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetScreenshot(ctx, request.(GetScreenshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetScreenshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetScreenshotResponseObject); ok {
		if err := validResponse.VisitGetScreenshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa63LbxvV/lR38/x+SGYqESDlm2OmHxLJdqb7VUpI2oUZcYA+JVRa78O6CFJvRTB+i",
	"T9gn6ZxdXBYkZFOKm8l0+skWsJdz/Z3fOeAvUaryQkmQ1kSzX6KCapqDBe3+OlfJGcP/MDCp5oXlSkaz",
	"6OyU3KiEcAbS8iUHTTTYUktgJNmSxbu3F5dkdKOSRTSIOG4oqM2iQSRpDtEs4iwaRBo+lFwDi2ZWlzCI",
	"TJpBTvEuuKV5ISCa/RTFx+cnf/7xL3+dvpy8Gb97+vrJ+68v4+9/+Nvzr6KrQWS3BR5nrOZyFd3d3dWn",
	"ONmfaaAWzlXyHj6UYKzTTqsCtOXgViyVzqn16i1pKSxKKlfRYEfdt6UtSkv88iF5d/rCkJQWttRAbAZk",
	"WQpBCroComFFNRNgDFFLssAX1/hiMYwGEcgyR6X8FQVb9ugwiJo9HbmWVBjYlevZrgwm1UoImgjw4mTA",
	"V5klXBoLlKFIN6Wxbv2aw6ZQ2g7n8kymGqgBQ3LIld6S0uBmtJXSeBUVYkus8mcKkCubDecyaoRPlBJA",
	"JUrvb+yIPo3jXcG/ry5vBSQFvwVh0Ew5veU5Wmp8/FU8iHIuqz9P4uZGLi2sQOONpRb7AXqZAfnu/SsU",
	"2qQaQJpM2SF5jdonQCjRQNPMGSqztiBKu38NbnKuakPQPZ+NRituszIZpipHt9WhE5WaRz1e3HBms44Z",
	"jsfT++3glt9jhsn0JDTDZNxjhrswn35yNmljSyU3kFqUKkgJUyhpYD8nwFieUwvs2gfDdZ7sm/d5vaiO",
	"GJtx4yBhw4UgGgzoNZClVrkLtkIxkpRsBXYuNxkXLrhSMIbL1ZCcSW9NF2lESbH10dU6YXI8vurz/Y1K",
	"rnkPPn0n+YcSyNlpCFFLpZ0wNyrZcfGDUGYQGUttaXpQUXLLqSD+PeGGULGhW0MWH0oogXVAwD/6yPnX",
	"vYH9TMk1SA4ybQK8UEI45dD+fu+OfgjFo4dBaTeeKjs3qndkHPTGTF/4Pdda6Y+EHr7eV/lPZU7lkQbK",
	"XL4GLxHQNhm1ZAPSko1WcrWjeSnhtoAUI9WdTlSallr3Gn5HZy9NnxrnKtkXnpXaRfB13hMZl8pSEcQ8",
	"sTwHTPecC8ENpEoyMyRvEMNLabkgSy65yYB19XlyPI57E+Ew03kT5GAQ34fkrRRbUmCyovUykEHkLpaU",
	"izpkW3umSlq4tYQBZYJLIHCbAjBgM18cGGdEKkuEooxsuM24JJPY9Ib5QUjz2uNLhSisD1KqxPYANDwI",
	"N2rrXtfVP7zyB7REBRSNH8gXpkxTV9c1QduUGr6sPFYhGkiGrlU6BLcoKBWMWjhCz/cVjJaLPIImtBo7",
	"nnD18crcrp7G8Sdw9fEoWTm1NOjgHs9+k9qSipZyABsQDanSDBihSwsNWhNkqAIsdFOEKQldd4+nT3vV",
	"8Vj7aWdvqCE0TaGwnsjic4w7nsLhjmz5Rj+CV6i9BJtm/oZmA1ly8am8RK13s3LUHjF6eC3T9hDbVAs7",
	"hTuIfmOx8HtDP8BWTSX9fw3LaBb936jtRkYVlx+dq+TCL2zp3ucjaO1JyNCuPsmtmlroa191T31gk2dh",
	"hgZ1sw/0wgC9p95c3EM5jhpuQf71j3+SDeUWMQgRka4pr1oBVfO0uTwii9aDftOzTCusRhj7lq9BINxK",
	"BtoVqsy3Em6niz23J4hZbpBMM9cgMLWRCP1udVVB3HqMIJCpKqUFjfktSSkx29eg29LkWV+XIA2iVl5s",
	"zJREe/qz7+kBuVyqfVNdgFgeZcpgELfiH1FzRI/qJJ/LufyGCHTgxncmOU+1ql4Ti1zD0p/BkA0khtsw",
	"eQ1Zc0oyLIxYJrxVB4RKRiSsQZO3b18bwq0BsXTgomn6M5q4QsACdOUAkmi1MaBd30alkysaRIKnUPGm",
	"qo9+fXaJ8WG5xfiNLpwsL1U0iNagjVc7Hh4PY1ylCpC04NEsmgzjYYyGpTZzMYX80DEaZWwfUCMiGkJD",
	"r2vfUzv1eJ4D49T6yLGllrgYXX52OpzLywpBuKnwwW1yjULSNALAPNKBVOUq64QsBmYdy0PyDtnu4uVz",
	"P2AY/cLZ3QJDz5kTT1tpMMZbDPmZI2VnDKlz3fxUwwcw9lvFtqiwozXS6U6LQvDU7RrdGDRAAxHOVgk1",
	"PMX/mDLPqd5Gs+hbfBQYB+1PRQnhiKGq5nURdj2xg7I++GrQCRHpLiz210gHOpe/aGYP705f9N/Mlh00",
	"quYttShf74siYWOG21TlCZfUKr0j1MlJHMxaPoXee2OYuy6iojTugW8LnJHH8fhwt9zbtU6Oxy2V+Rh9",
	"aQtRizphE/bJBuoxxqi6IGeNbsKdq6SlIZgrlVB3g+gkjh9oGN8YRFyuqeCMlFrMSN6MQfzDvRHI4Qp1",
	"W7oeZc6qi2vASBTb4l2lNGVRKMcpqhtPjiePUw52xxFfHE/jOE++rNoTQ6xrwKp+4YunX03z5MvPqCRC",
	"XKUgsGa0Rgz/O7QitGSyFrOSB6TlGtzU47Keo6SqFHXh0KXcGSy6Hlb6NguhDo03Hj/OeH70VIdEAnYD",
	"IMlkHLvQm0xP4s9oqPdhFHBTxd/5xds3JCmta6wMMZBTaXnq3zoFUIQnB8X+ZxL0u3Zw4DpP7RmKY4Mt",
	"+F6USc5ttzLeuAJj6cogizlXiYmucFdTrlC2FfQU2vdV7cRIqT2MMATocldQq/Lnml2QrFBcWt8NzeXC",
	"I9YCzQrcZqBrwqZ0284jw3G8Plzu1w0IJYtu97IgSw6C4RouU1EyYHPpbnXcUFWFOGg/XD3uq74vwfrS",
	"G35g+KnfS+2Skf8AcXe1VyDiB9ZtRxw7lfM86CwZqdp7LJPbsIx25jpPjsdxM2yRpRCDj1SezpABS9rJ",
	"UXx8dPzk8jiexfEsnv4Y9kmeHwRVupr4dxjDYcVst/MeT592euAeWWKUZbdzPbSv7HaRPadPfgxLbEXh",
	"H8B+PNnfc171/D5nTeI4br316NHVr3DxZPJbudjH4iN87Dc+yH+N2Q/3YNDC7aegRzrsHUopfZfX79Aq",
	"4R6RfX7xf5sjOo3x4c6o2OSeI8LhgVfrf54Ihd7vEQ61+cH8CSvkPQ3BUpWSuVlKmkH6c1u/fYVGp3U4",
	"g+8WTh7HCZGBIha6Sz8j/Xuj/FDd6YIY67jOiq9BkrPT3ynJewk2+LTWz+12GNC9FO/CaqC5p3iabnZn",
	"v35wF7AS5Hx+grJ45k1ydLktYOHmTKCbKcqC53QFo0KuPN0LjVaw5WIuGTQfKPxQ1+dg0LZsdkfhqWtW",
	"meOMNTc9iU8IXzbLmALjIgVuubEDklH/Z6vBFuxgLpWudwUa4+IEmw0Gfi0rAUnl5eUrArcF19t7iORF",
	"OGr5DfhkPXRpoq7Br4RL6nBy/1ti45GHbt0L04udIDEuiNw0CYPA/9ilio5TbgpluN+5F33lauV9jedI",
	"mvuAq6e24UeFiFpL0ywHaf/QrP7jPDKSFm5uej8WDwu5mkdRCBr71qnlfeV+TbIv6gunKPbPXJJka8H0",
	"HRjO6MP86PmOePb6OcFd2Et147BzcD19br032AuFvqnzr0HbICX+E6B70XN8M5TP6TbMX/zTf8pJwt9o",
	"DBBUMC3xfUbX4PPTz6R+h5B9WkX0Lr4G4N1axWE4bnfneRTpXvpKpVQQBmsQqsCU6NT+2WgkcEGmjJ1N",
	"42ns4KW6Zz8F/cRAMsKlQU12Zgem/Zmcqy93g54xgeawDkfnO2oGZ4Rq3l3d/TsAAP//4KFJSu4nAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
