//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for CreateJobRequestFormat.
const (
	CreateJobRequestFormatPdf CreateJobRequestFormat = "pdf"
	CreateJobRequestFormatPng CreateJobRequestFormat = "png"
)

// Defines values for CreateJobResponseStatus.
const (
	CreateJobResponseStatusPending CreateJobResponseStatus = "pending"
)

// Defines values for JobFormat.
const (
	JobFormatPdf JobFormat = "pdf"
	JobFormatPng JobFormat = "png"
)

// Defines values for JobStatus.
const (
	JobStatusDone       JobStatus = "done"
	JobStatusFailed     JobStatus = "failed"
	JobStatusPending    JobStatus = "pending"
	JobStatusProcessing JobStatus = "processing"
)

// CreateJobRequest defines model for CreateJobRequest.
type CreateJobRequest struct {
	// Format Output format. PDFs capture the full page regardless of `full_page`.
	Format *CreateJobRequestFormat `json:"format,omitempty"`

	// FullPage Capture the full scrollable page height instead of just the viewport.
	// Increases memory usage proportionally to page length.
	FullPage *bool `json:"full_page,omitempty"`

	// Height Viewport height in pixels.
	Height *int `json:"height,omitempty"`

	// URL The URL to screenshot. Must be a reachable http or https URL.
	URL string `json:"url"`

	// Width Viewport width in pixels.
	Width *int `json:"width,omitempty"`
}

// CreateJobRequestFormat Output format. PDFs capture the full page regardless of `full_page`.
type CreateJobRequestFormat string

// CreateJobResponse defines model for CreateJobResponse.
type CreateJobResponse struct {
	// JobID Unique ID identifier for the job.
	JobID string `json:"job_id"`

	// Status Initial status is always `pending`.
	Status CreateJobResponseStatus `json:"status"`

	// StatusURL Convenience URL to poll for job status.
	StatusURL string `json:"status_url"`
}

// CreateJobResponseStatus Initial status is always `pending`.
type CreateJobResponseStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Human-readable description of what went wrong.
	Error string `json:"error"`
}

// Job defines model for Job.
type Job struct {
	// CreatedAt When the job was created.
	CreatedAt time.Time `json:"created_at"`

	// Error Human-readable error message. Only present when status is `failed`.
	Error *string `json:"error,omitempty"`

	// FinishedAt When the job finished (success or failure). Null while pending or processing.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	Format     JobFormat  `json:"format"`
	FullPage   bool       `json:"full_page"`
	Height     int        `json:"height"`
	JobID      string     `json:"job_id"`

	// ScreenshotURL URL to fetch the screenshot file. Only present when status is `done`.
	ScreenshotURL *string `json:"screenshot_url,omitempty"`

	// StartedAt When the job started processing. Null while still pending.
	StartedAt *time.Time `json:"started_at,omitempty"`

	// Status - `pending` — waiting for available pod memory
	// - `processing` — Chrome is actively rendering the page
	// - `done` — screenshot is ready to download
	// - `failed` — job encountered an unrecoverable error
	Status JobStatus `json:"status"`
	URL    string    `json:"url"`
	Width  int       `json:"width"`
}

// JobFormat defines model for Job.Format.
type JobFormat string

// JobStatus - `pending` — waiting for available pod memory
// - `processing` — Chrome is actively rendering the page
// - `done` — screenshot is ready to download
// - `failed` — job encountered an unrecoverable error
type JobStatus string

// JobID defines model for JobId.
type JobID = string

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = CreateJobRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Submit a screenshot job
	// (POST /v1/job)
	CreateJob(w http.ResponseWriter, r *http.Request)
	// Get job status
	// (GET /v1/job/{id})
	GetJobStatus(w http.ResponseWriter, r *http.Request, id JobID)
	// Download screenshot file
	// (GET /v1/screenshot/{id})
	GetScreenshot(w http.ResponseWriter, r *http.Request, id JobID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateJob operation middleware
func (siw *ServerInterfaceWrapper) CreateJob(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJobStatus operation middleware
func (siw *ServerInterfaceWrapper) GetJobStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJobStatus(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetScreenshot operation middleware
func (siw *ServerInterfaceWrapper) GetScreenshot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetScreenshot(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/v1/job", wrapper.CreateJob)
	m.HandleFunc("GET "+options.BaseURL+"/v1/job/{id}", wrapper.GetJobStatus)
	m.HandleFunc("GET "+options.BaseURL+"/v1/screenshot/{id}", wrapper.GetScreenshot)

	return m
}

type CreateJobRequestObject struct {
	Body *CreateJobJSONRequestBody
}

type CreateJobResponseObject interface {
	VisitCreateJobResponse(w http.ResponseWriter) error
}

type CreateJob202JSONResponse CreateJobResponse

func (response CreateJob202JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob400JSONResponse ErrorResponse

func (response CreateJob400JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob413JSONResponse ErrorResponse

func (response CreateJob413JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob422JSONResponse ErrorResponse

func (response CreateJob422JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob500JSONResponse ErrorResponse

func (response CreateJob500JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetJobStatusRequestObject struct {
	ID JobID `json:"id"`
}

type GetJobStatusResponseObject interface {
	VisitGetJobStatusResponse(w http.ResponseWriter) error
}

type GetJobStatus200JSONResponse Job

func (response GetJobStatus200JSONResponse) VisitGetJobStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetJobStatus404JSONResponse ErrorResponse

func (response GetJobStatus404JSONResponse) VisitGetJobStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetJobStatus500JSONResponse ErrorResponse

func (response GetJobStatus500JSONResponse) VisitGetJobStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetScreenshotRequestObject struct {
	ID JobID `json:"id"`
}

type GetScreenshotResponseObject interface {
	VisitGetScreenshotResponse(w http.ResponseWriter) error
}

type GetScreenshot200ResponseHeaders struct {
	ContentDisposition string
	ContentLength      int
	ContentType        string
}

type GetScreenshot200ApplicationPdfResponse struct {
	Body          io.Reader
	Headers       GetScreenshot200ResponseHeaders
	ContentLength int64
}

func (response GetScreenshot200ApplicationPdfResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/pdf")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.Header().Set("Content-Type", fmt.Sprint(response.Headers.ContentType))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetScreenshot200ImagePngResponse struct {
	Body          io.Reader
	Headers       GetScreenshot200ResponseHeaders
	ContentLength int64
}

func (response GetScreenshot200ImagePngResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "image/png")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.Header().Set("Content-Type", fmt.Sprint(response.Headers.ContentType))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetScreenshot404JSONResponse ErrorResponse

func (response GetScreenshot404JSONResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetScreenshot500JSONResponse ErrorResponse

func (response GetScreenshot500JSONResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Submit a screenshot job
	// (POST /v1/job)
	CreateJob(ctx context.Context, request CreateJobRequestObject) (CreateJobResponseObject, error)
	// Get job status
	// (GET /v1/job/{id})
	GetJobStatus(ctx context.Context, request GetJobStatusRequestObject) (GetJobStatusResponseObject, error)
	// Download screenshot file
	// (GET /v1/screenshot/{id})
	GetScreenshot(ctx context.Context, request GetScreenshotRequestObject) (GetScreenshotResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateJob operation middleware
func (sh *strictHandler) CreateJob(w http.ResponseWriter, r *http.Request) {
	var request CreateJobRequestObject

	var body CreateJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateJob(ctx, request.(CreateJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateJobResponseObject); ok {
		if err := validResponse.VisitCreateJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJobStatus operation middleware
func (sh *strictHandler) GetJobStatus(w http.ResponseWriter, r *http.Request, id JobID) {
	var request GetJobStatusRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJobStatus(ctx, request.(GetJobStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJobStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobStatusResponseObject); ok {
		if err := validResponse.VisitGetJobStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetScreenshot operation middleware
func (sh *strictHandler) GetScreenshot(w http.ResponseWriter, r *http.Request, id JobID) {
	var request GetScreenshotRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetScreenshot(ctx, request.(GetScreenshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetScreenshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetScreenshotResponseObject); ok {
		if err := validResponse.VisitGetScreenshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xa624buRV+FYLtjwSQpbGlZL0q+mM3TlK7cZzGzm6byLA4wyMNnRlyQnIkq4GBPkSf",
	"sE9SHHKu0iiWve52scACa83wcm78vu9w8pVGKs2UBGkNHX+lGdMsBQva/TpR4THHPziYSIvMCiXpmB4f",
	"kWsVEsFBWjEToIkGm2sJnIQrMn13dn5BBov9wbUKp7RHBc7JmI1pj0qWAh1TwWmPaviSCw2cjq3OoUdN",
	"FEPKcDu4YWmWAB1/osH+yeivH//298PXw7cH7747ffb++4vgp5//8fI5vexRu8pwOWO1kHN6e3tbruLM",
	"f6GBWThR4Xv4koOxzkGtMtBWgBsxUzpl1ns4Y3li0VI5p701j89ym+WW+OF98u7olSERy2yugdgYyCxP",
	"EpKxORANc6Z5AsYQNSNTfHGFL6Z92qMg8xSd8ltkfNbhQ49Wc1p2zVhiYN2uF+s2mEirJGFhAt6cGMQ8",
	"tkRIY4FxNOk6N9aNXwhYZkrb/kQey0gDM2BICqnSK5IbnIyxUhq3YkmyIlb5NROQcxv3J5JWxodKJcAk",
	"Wu93bJl+GATrhv9UbF4bSDJxA4nBMKXsRqQYqYP950GPpkIWP0dBtaOQFuagccdcJ5s1ehED+fD+DRpt",
	"Ig0gTaxsn5yi9yEQRjSwKHaBiq3NiNLu/wYnuVTVJeiejweDubBxHvYjlWLaytKhuRa0I4tLwW3cCsP+",
	"weH2OLjhW8IwPBw1wzA86AjDbfM8fXIxqWtLhdcQWbSqcSRMpqSBzTNxrcIr0XHqP0jxJQdyfNQ8+DOl",
	"XTFdq3Atavc6uD1qLLO56cAaKaxgCfHviTCEJUu2MmSageRCztsHyz/7xg5XndXyQskFSAEyqqomU0ni",
	"3EOo83PXPCwgbnA/iGrnqQh25X/LzK4EvtRa6e3JA3y96d9f8pTJPQ2Mu4pvvERIWMbMkiVIS5Zayfma",
	"m7mEmwwiC5y41YmKolyj/Xd6563pcuNEhZvGR644+VWJyE0Pfo5BlpVGlsyQYjAaWx1FzizsWZFC14Hc",
	"LTTexRQMImCfnMlkRTINxkUHbagLcTpjIgE+XYtXpKSFG0s4MJ4ICQRuIgAOfOzhkwtOpLIkUYyTpbCx",
	"kGQYmG4qEFKYeJeQlCPJE5NHkaMfTdDAXMPTPnmL5LCMBfKCPyP4PtMKhwqf893CWFPmA9isDpOjs8tv",
	"E0g9+jAILrugv8aqX4A8FT10Y0OBBzOwUezCXU8gM5HcVSRcSVgvkUG9xOD+OKl3OiPFwGaOm1VgrEDJ",
	"4mth9+zXMP1HDTM6pn8Y1AJyUGivwYkKz/3Amp4fj1DrlZBRL+/kwgpj0ZJqn3LBquCapdrA4wYobQGy",
	"8y3UtVdzFPnPv/5NlkxYPHhIKmzBRCHTFC9U10TijCpdftKLWKsUHO9FViwgWRENkgNGxeUa7XUzXaG5",
	"OY0CFQaFDnfijaulRNBxowvscuOxXEBGKpcWNHDCJMmlhkgtQNeg6PTeOtH2aG0wqmYlMXh+8S0CXciZ",
	"2gzWOSSzvVgZLNna/j1m9tieAb0QEfQnciJ/IAlma+llYyoirYrXxCKNWfYZDFlCaIRtHlVDFoKRGDEZ",
	"wdGHtUeY5ETCAjQ5Ozs1RFgDyQy7GKtZ9BljXCjiDHSRARJqtTSgnahm0tlFezQRERSUXDQ5p8cXWCFW",
	"WCxWeu5sea1ojy5AG+920N/vBzhKZSBZJuiYDvtBP8DAMhu7qip0huNLZTrO/Q9RBJk1hDUzr33P4zwU",
	"aQpcMOurB1s1HIxpPz7qT+RFARnCkC855K4CkJqSBKVykWDgHtpAqnwet8oWi7Os5z55h8Jp+vpl1QMO",
	"vgp+O8UKdEHFBecajPFxQwHA0BHsNGt9WvSHYOyPiq+cOkBelc59lmWJiNyswbXBGFSo4CIWMiMi/MPk",
	"acr0io7pj/ioER/MAktyaHaBBZOVBOTaFodeXYhVARKC0G2T6K6QClubv6raw3dHr7p35rMWABUtcWnK",
	"95umSFia/ipSaSgks0qvGTUaBY12+C7A3uiUb9sgita4B153uiAfBAe7p6XZWHyLoGuGaUBMU7nvorof",
	"4nYhqJ3f7dN1okLC3AkrDoY/I7jLKAjuF4JCg1IhFywRnOQ6GZO06kn9w41+dHeH2t1BhzPHxcYlOoSK",
	"r3CvXJo8w0YUeLnjaH/4MOfAWJEiZ5bY+WT/MAjS8GmhhA2xyrKEhDmfgyVPvnt+mIZPH9FJxLPCQeDV",
	"PQcx4p9Qm4BCriCOwszCHuxtNSQrB4zCOGSMVJ6URKFzuXbL49oh6RU9ghoG7+DgYcHz9wBlSYRglwCS",
	"DA8CV3rDw1HwiIF636wCYYr6Ozk/e0vC3Lr2wRADKZNWRP6tcwBNeLZT7T+SoR/qHhSTBtpLEif1apg9",
	"z8NU2DYNXjsqsWxuULacqNDQS5zV5CY0bw4dxPq+4EosljLJCEaAWXcEWtCdxUIByTMlpCW5tCKZyKnH",
	"rSlGFoSNQZciTem6eURR44R7c7gf1yOMTNvtyZTMBCQcxwgZJTkHPpFuV6cHVU28jRbD8W8X274GW+vX",
	"Xuvy91N3xuohA385fHu5QQvBPdnaicYWX564I4cDXMZ9Q4vkuGqSZ/O6ANlotBfs7+0/u9gPxgH+95FW",
	"Tb/Mk2Stm+6Ycfix2Qd5MdCg5OIGtiUPduS0tRZz1waw3e51WDz82GTMQn3fQ7J4nb4R++L5PWPNc19a",
	"V6mh42EQYHxKWHvopcidSRsOf62k+Rq6V0KqOO6eklL1bOSk2T16wnq8s1A8+r8EsXqyrvruEbO6Bd2E",
	"EQ/b2PjkUvqVfwdRu7P0Wm35rqHcWVlgg7ZFKs9ULrm7VohiiD7XtOaJC8u3RaVeR48eppZQmyFsuE0f",
	"URi9Vf5S1fmCcOQkwFwsQJLjo9+o/HkNtvGxYqvqWRMGW8XPudXAUi9+NFuuX3v6a6wGTaMa8ncJ0xc+",
	"KnsXqwym7tIFdHWfMBUpm8Mgk3MvhJpxy/hsOpEcqjtqf5/pz1hD0y+3fQ1ANVWqtlEwImJWDeMKjCsW",
	"uBHG9kjM/M/agxXY3kQqXc5qeIyDQ1TiHPxYngPKrYuLNwRuMqFXW/TVefPG4VcQWOXdQ1V4FT6FQjJH",
	"GpvfbKqM3HfqRqWerxWJcUXkLlWwCPxn+aI6joTJlBF+5kb15fO5zzWuI1nqC668w2zep1NmLYviFKT9",
	"UzX6zxNqJMvcJeJ2rO1ncj6htIkbm9Ep7X3jvntvmvrKOYrNpZAkXFkwXQs2b6eb52NzvdPj05cEZ2GX",
	"0a7D1sLlXWydvd5GKXRdwf4SwG0cif8F7p53LF9dUads1Ty/+NN/xagvKYWc9xBU8Fji+5gtwJ9Pf2Hz",
	"G0Tto6Ki1/G1gd91VByM43S3nkeR9qZvVMQSwmEBicrwSLTofzwYJDggVsaOD4PDwMFLsc/mEfTttORE",
	"SIOerDXWpv4HPY5ibnsdDbQWsGheIq+52Vij6ebt5e1/AwAA//9ncXlhmyQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
