//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for CreateJobRequestFormat.
const (
	CreateJobRequestFormatPdf CreateJobRequestFormat = "pdf"
	CreateJobRequestFormatPng CreateJobRequestFormat = "png"
)

// Defines values for CreateJobResponseStatus.
const (
	CreateJobResponseStatusPending CreateJobResponseStatus = "pending"
)

// Defines values for JobFormat.
const (
	JobFormatPdf JobFormat = "pdf"
	JobFormatPng JobFormat = "png"
)

// Defines values for JobStatus.
const (
	JobStatusDone       JobStatus = "done"
	JobStatusFailed     JobStatus = "failed"
	JobStatusPending    JobStatus = "pending"
	JobStatusProcessing JobStatus = "processing"
)

// CreateJobRequest defines model for CreateJobRequest.
type CreateJobRequest struct {
	// Format Output format. PDFs capture the full page regardless of `full_page`.
	Format *CreateJobRequestFormat `json:"format,omitempty"`

	// FullPage Capture the full scrollable page height instead of just the viewport.
	// Increases memory usage proportionally to page length.
	FullPage *bool `json:"full_page,omitempty"`

	// Height Viewport height in pixels.
	Height *int `json:"height,omitempty"`

	// URL The URL to screenshot. Must be a reachable http or https URL.
	URL string `json:"url"`

	// Width Viewport width in pixels.
	Width *int `json:"width,omitempty"`
}

// CreateJobRequestFormat Output format. PDFs capture the full page regardless of `full_page`.
type CreateJobRequestFormat string

// CreateJobResponse defines model for CreateJobResponse.
type CreateJobResponse struct {
	// JobID Unique ID identifier for the job.
	JobID string `json:"job_id"`

	// Status Initial status is always `pending`.
	Status CreateJobResponseStatus `json:"status"`

	// StatusURL Convenience URL to poll for job status.
	StatusURL string `json:"status_url"`
}

// CreateJobResponseStatus Initial status is always `pending`.
type CreateJobResponseStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Human-readable description of what went wrong.
	Error string `json:"error"`
}

// Job defines model for Job.
type Job struct {
	// CreatedAt When the job was created.
	CreatedAt time.Time `json:"created_at"`

	// Error Human-readable error message. Only present when status is `failed`.
	Error *string `json:"error,omitempty"`

	// FinishedAt When the job finished (success or failure). Null while pending or processing.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	Format     JobFormat  `json:"format"`
	FullPage   bool       `json:"full_page"`
	Height     int        `json:"height"`
	JobID      string     `json:"job_id"`

	// ScreenshotURL URL to fetch the screenshot file. Only present when status is `done`.
	ScreenshotURL *string `json:"screenshot_url,omitempty"`

	// StartedAt When the job started processing. Null while still pending.
	StartedAt *time.Time `json:"started_at,omitempty"`

	// Status - `pending` — waiting for available pod memory
	// - `processing` — Chrome is actively rendering the page
	// - `done` — screenshot is ready to download
	// - `failed` — job encountered an unrecoverable error
	Status JobStatus `json:"status"`
	URL    string    `json:"url"`
	Width  int       `json:"width"`
}

// JobFormat defines model for Job.Format.
type JobFormat string

// JobStatus - `pending` — waiting for available pod memory
// - `processing` — Chrome is actively rendering the page
// - `done` — screenshot is ready to download
// - `failed` — job encountered an unrecoverable error
type JobStatus string

// JobID defines model for JobId.
type JobID = string

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = CreateJobRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Submit a screenshot job
	// (POST /v1/job)
	CreateJob(w http.ResponseWriter, r *http.Request)
	// Get job status
	// (GET /v1/job/{id})
	GetJobStatus(w http.ResponseWriter, r *http.Request, id JobID)
	// Download screenshot file
	// (GET /v1/screenshot/{id})
	GetScreenshot(w http.ResponseWriter, r *http.Request, id JobID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateJob operation middleware
func (siw *ServerInterfaceWrapper) CreateJob(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJobStatus operation middleware
func (siw *ServerInterfaceWrapper) GetJobStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJobStatus(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetScreenshot operation middleware
func (siw *ServerInterfaceWrapper) GetScreenshot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetScreenshot(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/v1/job", wrapper.CreateJob)
	m.HandleFunc("GET "+options.BaseURL+"/v1/job/{id}", wrapper.GetJobStatus)
	m.HandleFunc("GET "+options.BaseURL+"/v1/screenshot/{id}", wrapper.GetScreenshot)

	return m
}

type CreateJobRequestObject struct {
	Body *CreateJobJSONRequestBody
}

type CreateJobResponseObject interface {
	VisitCreateJobResponse(w http.ResponseWriter) error
}

type CreateJob202JSONResponse CreateJobResponse

func (response CreateJob202JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob400JSONResponse ErrorResponse

func (response CreateJob400JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob413JSONResponse ErrorResponse

func (response CreateJob413JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob422JSONResponse ErrorResponse

func (response CreateJob422JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob500JSONResponse ErrorResponse

func (response CreateJob500JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetJobStatusRequestObject struct {
	ID JobID `json:"id"`
}

type GetJobStatusResponseObject interface {
	VisitGetJobStatusResponse(w http.ResponseWriter) error
}

type GetJobStatus200JSONResponse Job

func (response GetJobStatus200JSONResponse) VisitGetJobStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetJobStatus404JSONResponse ErrorResponse

func (response GetJobStatus404JSONResponse) VisitGetJobStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetJobStatus500JSONResponse ErrorResponse

func (response GetJobStatus500JSONResponse) VisitGetJobStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetScreenshotRequestObject struct {
	ID JobID `json:"id"`
}

type GetScreenshotResponseObject interface {
	VisitGetScreenshotResponse(w http.ResponseWriter) error
}

type GetScreenshot200ResponseHeaders struct {
	ContentLength int
	ContentType   string
}

type GetScreenshot200ApplicationPdfResponse struct {
	Body          io.Reader
	Headers       GetScreenshot200ResponseHeaders
	ContentLength int64
}

func (response GetScreenshot200ApplicationPdfResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/pdf")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.Header().Set("Content-Type", fmt.Sprint(response.Headers.ContentType))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetScreenshot200ImagePngResponse struct {
	Body          io.Reader
	Headers       GetScreenshot200ResponseHeaders
	ContentLength int64
}

func (response GetScreenshot200ImagePngResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "image/png")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.Header().Set("Content-Type", fmt.Sprint(response.Headers.ContentType))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetScreenshot404JSONResponse ErrorResponse

func (response GetScreenshot404JSONResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetScreenshot500JSONResponse ErrorResponse

func (response GetScreenshot500JSONResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Submit a screenshot job
	// (POST /v1/job)
	CreateJob(ctx context.Context, request CreateJobRequestObject) (CreateJobResponseObject, error)
	// Get job status
	// (GET /v1/job/{id})
	GetJobStatus(ctx context.Context, request GetJobStatusRequestObject) (GetJobStatusResponseObject, error)
	// Download screenshot file
	// (GET /v1/screenshot/{id})
	GetScreenshot(ctx context.Context, request GetScreenshotRequestObject) (GetScreenshotResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateJob operation middleware
func (sh *strictHandler) CreateJob(w http.ResponseWriter, r *http.Request) {
	var request CreateJobRequestObject

	var body CreateJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateJob(ctx, request.(CreateJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateJobResponseObject); ok {
		if err := validResponse.VisitCreateJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJobStatus operation middleware
func (sh *strictHandler) GetJobStatus(w http.ResponseWriter, r *http.Request, id JobID) {
	var request GetJobStatusRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJobStatus(ctx, request.(GetJobStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJobStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobStatusResponseObject); ok {
		if err := validResponse.VisitGetJobStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetScreenshot operation middleware
func (sh *strictHandler) GetScreenshot(w http.ResponseWriter, r *http.Request, id JobID) {
	var request GetScreenshotRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetScreenshot(ctx, request.(GetScreenshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetScreenshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetScreenshotResponseObject); ok {
		if err := validResponse.VisitGetScreenshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xa627bRvZ/lQH//w8toAttqamrb2mcZO3EsTdy2m5iwxpyjsRxyBlmLpK1gYF9iH3C",
	"fZLFmaHIkUTHsuvtFgsUqEXO5dx/v3OYr1Eqi1IKEEZHo69RSRUtwIByv45lcsTwDwY6Vbw0XIpoFB0d",
	"kmuZEM5AGD7loIgCY5UARpIlmZydjs9Jf77Xv5bJJOpEHPeU1GRRJxK0gGgUcRZ1IgVfLFfAopFRFjqR",
	"TjMoKF4HN7Qoc4hGn6J473j45uNffzt4PXi3f/bjyQ/vfzqPf/n1by+fRZedyCxLPE4bxcUsur29XZ3i",
	"xH+hgBo4lsl7+GJBG6egkiUow8GtmEpVUOM1nFKbG5RUzKLOhsan1pTWEL+8R84OX2mS0tJYBcRkQKY2",
	"z0lJZ0AUzKhiOWhN5JRM8MUVvpj0ok4EwhaolL+iZNMWHTpRvWdNrinNNWzK9WJTBp0qmec0ycGLkwGf",
	"ZYZwoQ1QhiJdW23c+jmHRSmV6V2II5EqoBo0KaCQakmsxs1oK6nwKprnS2KkPzMHMTNZ70JEtfCJlDlQ",
	"gdL7G9dEP4jjTcF/qS5vBCQlv4Fco5kKesMLtNT+3rO4ExVcVD+HcX0jFwZmoPBGq/LtGD3PgHx4/xaF",
	"1qkCEDqTpkdOUPsECCUKaJo5Q2XGlEQq93+Nm5yrmhB0z0f9/oybzCa9VBbotlXoRFbxqMWLC85MtmaG",
	"vf2Du+3glt9hhsHBMDTDYL/FDLdhPn1yNmliSybXkBqUKkgJXUqhYTsnrmVyxVuy/oPgXyyQo8Mw8adS",
	"uWC6lsmG1R6UuJ1IG2qsbqk1ghtOc+LfE64JzRd0qcmkBMG4mK0nln/2jRuuWqPlhRRzEBxEWkdNKfPc",
	"qYelzu/d0LAqcf2Hlah1P1XGrvVfE7PNgS+Vkupu5wG+3tbvL7agoquAMhfxwUssCYuMGrIAYchCSTHb",
	"UNMKuCkhNcCIO53INLUK5b9XOy9NmxrHMtkWPnXBya5WFTnU4NcMxCrSyIJqUi1GYetUZNRA1/AC2hJy",
	"N9N4FQvQWAF75FTkS1Iq0M46KEMTiJMp5TmwyYa9UikM3BjCgLKcCyBwkwIwYCNfPhlnREhDckkZWXCT",
	"cUEGsW6HAi64znYxyWol+U7bNHXwowgKaBV83yPvEBwWGUdc8DmC70slcSn3Pt/NjA1kPgLNGjM5OLv8",
	"NoA0qw/i+LKt9De16ndUnhoe2mtDVQ+mYNLMmbvZQKY8vy9ImBSwGSL95oj+w+uk2ilHqoWhj8Mo0IYj",
	"ZfGxsLv3mzL9/wqm0Sj6v35DIPsV9+ofy2TsFzbw/HSA2pyEiHp5LxbWNRYlqe9ZHVgHXBiqQT0OitId",
	"hWx8B3R1G4wi//rHP8mCcoOJh6BC55RXNE2yinVdCNxRu8tvepEpWYDDvdTwOeRLokAwQKs4X6O8bqcL",
	"NLcnCFCukegwR96YXAgsOm51VbvcegwXEKm0woACRqggVihI5RxUUxQd39sE2k7UCIysWQo0nj+8HR80",
	"pFZxsxxjrPi6/7zkb2D53Hr3unYhA8pANQ3Db93nZ0fdN7BsIoO6XZ70czGV2w4YQz7tZlJjGjQ26VLd",
	"pV0Nas5T6F2IC/Gc5BgBC09FC54qWb0mBqHR0M+gyQISzU2Y/prMOSUoquP73lUdQgUjAuagyOnpiSbc",
	"aMin2BkZRdPP6LeKZZegKq+SRMmFBuWIOhVOrqgT5TyFCuYrO5wcnWPUGW4wAaKxk+W1jDrRHJT2ase9",
	"vV6Mq2QJgpY8GkWDXtyL0VnUZM7kFXdxGCx1Sy15nqZQGk1oGE3K91FOQ14UwDg1PiKx/cPFGEpHh70L",
	"cV6VIa7JFwvWRRXCXZ4j/a6CBpgvlyCknWVrqYABv8qRHjlDMjZ5/bLuK/tfObudYFQ7o+KBMwVae7sh",
	"qaCoCHavDeetek7Q5mfJlo5xIFYLpz4ty5ynblf/WqMN6krjLJZQzVP8Q9uioGoZjaKf8VFgH/QCzS2E",
	"nWWFjitQc62Qq4htVbAucljYbkPwvEJ4Xbv8Vd1ynh2+ar+ZTdeKWtVmr0T5aVsUAQvdW6aySLigRqoN",
	"oYbDOGix7wOBre77dr0wozTugeeyzsj78f7ubgmblW+BfoNaQdkKu4FdmPxj1K5IutN7PbuOZUKoy7Aq",
	"MXyO4C3DOH6YCSpeG3ExpzlnxKp8RIq6z/UPt3rc3RVa7zhalDmqLl5Vh0SyJd5lhbYlNrfAVjcO9waP",
	"Uw604QXi8Kp2frd3EMdF8n3FrjUx0tCcJJbNwJDvfnx2UCTfP6GSWM8qBYHVsxOi+d+hEQHJYQUclZiV",
	"PNgvK8iXrjBy7SpjKm2+AgplxcbkyLVYwncJWNTQePv7jzOeny2sQiIBswAQZLAfu9AbHAzjJzTU+zAK",
	"uK7i73h8+o4k1riWRBMNBRWGp/6tUwBF+GGn2H8iQT80fS06DZSnOZ6k1GV2bJOCm3UYvHZQYuhMIxU6",
	"lomOLnFXiE0o3gxagPV9hZUYLCsnYzEC9LoD0AruDAYKCFZKLgyxwvD8Qkx83ZqgZYGbDNSK+EnVNKRI",
	"alwzEC736zqEksl6yzMhUw45wzVcpLllwC6Eu9VxTNkAb9C2OPxtQ9vXYBpO3FkbKH9q91izpO8HzreX",
	"W7AQPxCtHRFdw8tjl3K4wHncN8kIjssQPMMRBKLRsBvvdfd+ON+LRzH+9zGqBwnC5vlGh96y4+Bj2Ft5",
	"MhBAcjXVXaMHO2LaRtu6a1O53kK2SDz4GCJmxegfQFk899+yffX8gbZm1ofWVaGj0SCO0T6rsvbYQcu9",
	"ThsM/iin+Rh6kENqO+7ukhXr2fJJ2JF6wHq6XKge/VeMWD/ZZH0PsFnT1m6XEV+2sfGxQviT/wesdm/o",
	"rbX6u5pyZ2aBDdodVHkqrWBuVJFmkH5uYM0DF4bvGpR6Hj18HFtCboZlw136hMTonfSDWqcLliNHAWZ8",
	"DoIcHf5J6c9rMMEHkDtZzwYxuJP8jI0CWnjyo+hic5TqR2MBTCMb8rOEyQtvle75soQJ8fOhep4w4QWd",
	"Qb8UM0+EQruVbDq5EAzqubefkfocCzj94q4vDMimVqxtGA8Jn9bLmATtggVuuDYdklH/s9FgCaZzIaRa",
	"7Qo0xsUJMnEGfi2zgHTr/PwtgZuSq+Ud/GocThz+AIK1mj3UgVfXp4QLqpZR25yv9shDt25F6ngjSLQL",
	"IjdUwSDwn/qr6Hjrvk1vB94rtxGbNS5IsjTgPrXVUrVMkMN42z7v5OjkJcFdyNrX/bp28Gpe2lijs2Xa",
	"tn/H8HsKWBBi/4k6Nm45vh4jF3QZ5gP+9F8amqEfF7MOJimGOb7P6Bx8vPsByJ+wCh5Wk/PNehXUw8Yq",
	"riwGg26XluGI+9Ml5p+/ziftukxvZUpzwmAOuSwLtEGItqN+P8cFmdRmdBAfxC6bKzG26m3VvQpGuNCo",
	"6EYfq5sRu6vot52WflVxmIcz2w0rBGeEVri9vP13AAAA///cqkYxXiQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
