//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for CreateJobRequestFormat.
const (
	CreateJobRequestFormatPdf CreateJobRequestFormat = "pdf"
	CreateJobRequestFormatPng CreateJobRequestFormat = "png"
)

// Defines values for CreateJobResponseStatus.
const (
	CreateJobResponseStatusPending CreateJobResponseStatus = "pending"
)

// Defines values for JobFormat.
const (
	JobFormatPdf JobFormat = "pdf"
	JobFormatPng JobFormat = "png"
)

// Defines values for JobStatus.
const (
	JobStatusDone       JobStatus = "done"
	JobStatusFailed     JobStatus = "failed"
	JobStatusPending    JobStatus = "pending"
	JobStatusProcessing JobStatus = "processing"
)

// CreateJobRequest defines model for CreateJobRequest.
type CreateJobRequest struct {
	// Format Output format. PDFs capture the full page regardless of `full_page`.
	Format *CreateJobRequestFormat `json:"format,omitempty"`

	// FullPage Capture the full scrollable page height instead of just the viewport.
	// Increases memory usage proportionally to page length.
	FullPage *bool `json:"full_page,omitempty"`

	// Height Viewport height in pixels.
	Height *int `json:"height,omitempty"`

	// URL The URL to screenshot. Must be a reachable http or https URL.
	URL string `json:"url"`

	// Width Viewport width in pixels.
	Width *int `json:"width,omitempty"`
}

// CreateJobRequestFormat Output format. PDFs capture the full page regardless of `full_page`.
type CreateJobRequestFormat string

// CreateJobResponse defines model for CreateJobResponse.
type CreateJobResponse struct {
	// JobID Unique ID identifier for the job.
	JobID string `json:"job_id"`

	// Status Initial status is always `pending`.
	Status CreateJobResponseStatus `json:"status"`

	// StatusURL Convenience URL to poll for job status.
	StatusURL string `json:"status_url"`
}

// CreateJobResponseStatus Initial status is always `pending`.
type CreateJobResponseStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Human-readable description of what went wrong.
	Error string `json:"error"`
}

// Job defines model for Job.
type Job struct {
	// CreatedAt When the job was created.
	CreatedAt time.Time `json:"created_at"`

	// Error Human-readable error message. Only present when status is `failed`.
	Error *string `json:"error,omitempty"`

	// FinishedAt When the job finished (success or failure). Null while pending or processing.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	Format     JobFormat  `json:"format"`
	FullPage   bool       `json:"full_page"`
	Height     int        `json:"height"`
	JobID      string     `json:"job_id"`

	// ScreenshotURL URL to fetch the screenshot file. Only present when status is `done`.
	ScreenshotURL *string `json:"screenshot_url,omitempty"`

	// StartedAt When the job started processing. Null while still pending.
	StartedAt *time.Time `json:"started_at,omitempty"`

	// Status - `pending` — waiting for available pod memory
	// - `processing` — Chrome is actively rendering the page
	// - `done` — screenshot is ready to download
	// - `failed` — job encountered an unrecoverable error
	Status JobStatus `json:"status"`
	URL    string    `json:"url"`
	Width  int       `json:"width"`
}

// JobFormat defines model for Job.Format.
type JobFormat string

// JobStatus - `pending` — waiting for available pod memory
// - `processing` — Chrome is actively rendering the page
// - `done` — screenshot is ready to download
// - `failed` — job encountered an unrecoverable error
type JobStatus string

// JobID defines model for JobId.
type JobID = string

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = CreateJobRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Submit a screenshot job
	// (POST /v1/job)
	CreateJob(w http.ResponseWriter, r *http.Request)
	// Get job status
	// (GET /v1/job/{id})
	GetJobStatus(w http.ResponseWriter, r *http.Request, id JobID)
	// Download screenshot file
	// (GET /v1/screenshot/{id})
	GetScreenshot(w http.ResponseWriter, r *http.Request, id JobID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateJob operation middleware
func (siw *ServerInterfaceWrapper) CreateJob(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJobStatus operation middleware
func (siw *ServerInterfaceWrapper) GetJobStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJobStatus(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetScreenshot operation middleware
func (siw *ServerInterfaceWrapper) GetScreenshot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id JobID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetScreenshot(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/v1/job", wrapper.CreateJob)
	m.HandleFunc("GET "+options.BaseURL+"/v1/job/{id}", wrapper.GetJobStatus)
	m.HandleFunc("GET "+options.BaseURL+"/v1/screenshot/{id}", wrapper.GetScreenshot)

	return m
}

type CreateJobRequestObject struct {
	Body *CreateJobJSONRequestBody
}

type CreateJobResponseObject interface {
	VisitCreateJobResponse(w http.ResponseWriter) error
}

type CreateJob202JSONResponse CreateJobResponse

func (response CreateJob202JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob400JSONResponse ErrorResponse

func (response CreateJob400JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob413JSONResponse ErrorResponse

func (response CreateJob413JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob422JSONResponse ErrorResponse

func (response CreateJob422JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateJob500JSONResponse ErrorResponse

func (response CreateJob500JSONResponse) VisitCreateJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetJobStatusRequestObject struct {
	ID JobID `json:"id"`
}

type GetJobStatusResponseObject interface {
	VisitGetJobStatusResponse(w http.ResponseWriter) error
}

type GetJobStatus200JSONResponse Job

func (response GetJobStatus200JSONResponse) VisitGetJobStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetJobStatus404JSONResponse ErrorResponse

func (response GetJobStatus404JSONResponse) VisitGetJobStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetJobStatus500JSONResponse ErrorResponse

func (response GetJobStatus500JSONResponse) VisitGetJobStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetScreenshotRequestObject struct {
	ID JobID `json:"id"`
}

type GetScreenshotResponseObject interface {
	VisitGetScreenshotResponse(w http.ResponseWriter) error
}

type GetScreenshot200ResponseHeaders struct {
	ContentDisposition string
	ContentLength      int
	ContentType        string
}

type GetScreenshot200ApplicationPdfResponse struct {
	Body          io.Reader
	Headers       GetScreenshot200ResponseHeaders
	ContentLength int64
}

func (response GetScreenshot200ApplicationPdfResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/pdf")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.Header().Set("Content-Type", fmt.Sprint(response.Headers.ContentType))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetScreenshot200ImagePngResponse struct {
	Body          io.Reader
	Headers       GetScreenshot200ResponseHeaders
	ContentLength int64
}

func (response GetScreenshot200ImagePngResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "image/png")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.Header().Set("Content-Type", fmt.Sprint(response.Headers.ContentType))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetScreenshot404JSONResponse ErrorResponse

func (response GetScreenshot404JSONResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetScreenshot500JSONResponse ErrorResponse

func (response GetScreenshot500JSONResponse) VisitGetScreenshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Submit a screenshot job
	// (POST /v1/job)
	CreateJob(ctx context.Context, request CreateJobRequestObject) (CreateJobResponseObject, error)
	// Get job status
	// (GET /v1/job/{id})
	GetJobStatus(ctx context.Context, request GetJobStatusRequestObject) (GetJobStatusResponseObject, error)
	// Download screenshot file
	// (GET /v1/screenshot/{id})
	GetScreenshot(ctx context.Context, request GetScreenshotRequestObject) (GetScreenshotResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateJob operation middleware
func (sh *strictHandler) CreateJob(w http.ResponseWriter, r *http.Request) {
	var request CreateJobRequestObject

	var body CreateJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateJob(ctx, request.(CreateJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateJobResponseObject); ok {
		if err := validResponse.VisitCreateJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJobStatus operation middleware
func (sh *strictHandler) GetJobStatus(w http.ResponseWriter, r *http.Request, id JobID) {
	var request GetJobStatusRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJobStatus(ctx, request.(GetJobStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJobStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobStatusResponseObject); ok {
		if err := validResponse.VisitGetJobStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetScreenshot operation middleware
func (sh *strictHandler) GetScreenshot(w http.ResponseWriter, r *http.Request, id JobID) {
	var request GetScreenshotRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetScreenshot(ctx, request.(GetScreenshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetScreenshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetScreenshotResponseObject); ok {
		if err := validResponse.VisitGetScreenshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xa73Ibt/V9FQx+vw/JDEWuRDpR2OmHxLJdqZblWkrSOtSI2MUlF8ousAawpFiPZvoQ",
	"fcI+SecCy10subQo2U0znclMRC4WuP9wzrmX/kgTlRdKgrSGjj/SgmmWgwXtPp2p+JTjHxxMokVhhZJ0",
	"TE9PyK2KieAgrZgJ0ESDLbUETuIVmb69uLwig8Xh4FbFU9qjAt8pmE1pj0qWAx1TwWmPavhQCg2cjq0u",
	"oUdNkkLO8Di4Y3mRAR3/QqPDs9Gf3//lr8evhm+O3n57/uzdd1fRTz//7cU39LpH7arA7YzVQs7p/f39",
	"ehdn/nMNzMKZit/BhxKMdQ5qVYC2AtyKmdI5s97DGSszi5bKOe1teHxR2qK0xC/vk7cnLw1JWGFLDcSm",
	"QGZllpGCzYFomDPNMzCGqBmZ4oMbfDDt0x4FWebolD+i4LMOH3q0fqdl14xlBjbter5pg0m0yjIWZ+DN",
	"SUHMU0uENBYYR5NuS2Pd+oWAZaG07U/kqUw0MAOG5JArvSKlwZcxVkrjUSzLVsQqv2cGcm7T/kTS2vhY",
	"qQyYROv9iS3Tj6No0/CfqsMbA0kh7iAzGKac3YkcI3V0+E3Uo7mQ1cdRVJ8opIU5aDyx1Nl2jV6lQH58",
	"9xqNNokGkCZVtk/O0fsYCCMaWJK6QKXWFkRp93+DL7lUNSXovh8PBnNh0zLuJyrHtK1Lh5Za0I4sLgW3",
	"aSsMh0fHu+Pglu8Iw/B4FIZheNQRhvvwPv3iYtLUlopvIbFoVXAlTKGkge07caviG9Fx63+U4kMJ5PQk",
	"vPgzpV0x3ap4I2qPurg9aiyzpenAGimsYBnxz4kwhGVLtjJkWoDkQs7bF8t/94kTbjqr5bmSC5ACZFJX",
	"TaGyzLmHUOff3fCwgrjB4yCqnacq2LX/LTO7EvhCa6V3Jw/w8bZ/fypzJg80MO4qPniIkLBMmSVLkJYs",
	"tZLzDTdLCXcFJBY4cbsTlSSlRvsf9M5b0+XGmYq3jU9ccfKbNSKHHvycglxXGlkyQ6rFaGx9FTmzcGBF",
	"Dl0Xcr/QeBdzMIiAfXIhsxUpNBgXHbShKcTpjIkM+HQjXomSFu4s4cB4JiQQuEsAOPCxh08uOJHKkkwx",
	"TpbCpkKSYWS6qUBIYdJ9QrJeSb4yZZI4+tEEDSw1fN0nb5AclqlAXvB3BJ8XWuFS4XO+XxgbynwCmzVh",
	"cnR2/WkCaVYfR9F1F/Q3WPUZyFPTQzc2VHgwA5ukLtzNC2QmsoeKhCsJmyUyaLYYPB4n9V53pFoY5jis",
	"AmMFShZfC/tnv4Hp/9cwo2P6f4NGQA4q7TU4U/GlX9jQ85cj1GYnZNTrB7mwxli0pD5nvWFdcGGpBngc",
	"gNIOILvcQV0HDUeRf/3jn2TJhMWLh6TCFkxUMk3xSnVNJL5Rp8u/9DzVKgfHe4kVC8hWRIPkgFFxuUZ7",
	"3Zuu0Nw7QYEKg0KHO/HG1VIi6LjVFXa59VguIBNVSgsaOGGSlFJDohagG1B0em+TaHu0MRhVs5IYPL/5",
	"DoEu5ExtB+sSstlBqgyWbGP/ATMH7MCAXogE+hM5kd+TDLO19LIxF4lW1WNikcYs+xUMWUJshA2vqiEL",
	"wUiKmIzg6MPaI0xyImEBmlxcnBsirIFshl2M1Sz5FWNcKeICdJUBEmu1NKCdqGbS2UV7NBMJVJRcNTnn",
	"p1dYIVZYLFZ66Wx5pWiPLkAb73bUP+xHuEoVIFkh6JgO+1E/wsAym7qqqnSG40tlOu7990kChTWEhZnX",
	"vudxHoo8By6Y9dWDrRouxrSfnvQn8qqCDGHIhxJKVwFITVmGUrlKMHAPbSBVOU9bZYvFua7nPnmLwmn6",
	"6kXdAw4+Cn4/xQp0QcUN5xqM8XFDAcDQEew0G31a9Ydg7A+Kr5w6QF6Vzn1WFJlI3FuDW4MxqFHBRSxm",
	"RiT4hynznOkVHdMf8KsgPpgFlpUQdoEVk60JyLUtDr26EKsGJASh+5DobpAKW4e/rNvDtycvu0/msxYA",
	"VS3x2pTvtk2RsDT9VaLyWEhmld4wajSKgnb4IcDe6pTv2yCK1rgvvO50QT6KjvZPS9hYfIqgG4YJICZU",
	"7vuo7qe4XQlq53f7dp2pmDB3w6qL4e8InjKKoseFoNKgVMgFywQnpc7GJK97Uv/lVj+6v0Pt7qDDmdPq",
	"4DU6xIqv8KxSmrLARhT4+sTR4fBpzoGxIkfOXGPnV4fHUZTHX1dK2BCrLMtIXPI5WPLVt98c5/HXX9BJ",
	"xLPKQeD1nIMY8XdoTEAhVxFHZWZlD/a2GrKVA0ZhHDImqszWRKFLuTHlce2Q9IoeQQ2Dd3T0tOD5OcC6",
	"JGKwSwBJhkeRK73h8Sj6goF6F1aBMFX9nV1evCFxaV37YIiBnEkrEv/UOYAmPNur9r+QoT82PSgmDbSX",
	"JE7qNTB7Wca5sG0avHVUYtncoGw5U7Gh1/hWyE1o3hw6iPVdxZVYLOskIxgBZt0RaEV3FgsFJC+UkJaU",
	"0opsIqcet6YYWRA2Bb0WaUo3zSOKGifcw+V+XY8wMm23J1MyE5BxXCNkkpUc+ES6U50eVA3xBi2G498u",
	"tn0FttGvvdbw95fujDVLBn44fH+9RQvRI9naicYWX565K4cLXMZ9Q4vkuArJMxwXIBuNDqLDg8NnV4fR",
	"OML/3qMgLb27N7mh42eHR1E9B5Bllm002B2bHL8PWyOvDwKWroayLcWwJ81tdJ379oTtDrDD4uH7kEQr",
	"Qf4IFeOl+1Y6qu8/J/zDKIqa+D95TvJg0obD3yppvoYelZA6jvunZC2EtnISNpSewx6bn913ofrqvxLE",
	"+ptNIfiImDVd6TayeCTHXqiU0u/8PxC1B0uv1anvG8q9xQb2bDvU80yVkrtJQ5JC8mvDdJ7LsHxb7Oql",
	"9ehpAgrlGsKGO/QLaqU3ys9ZnS8IR04VzMUCJDk9+Z0qoldgg98vdgqhDa2wUw9dWg0s93pIs+XmJNRP",
	"tgLmRoHkxwvT5z4qB1erAqZuDgO6HjFMRc7mMCjk3GujMG4Fn00nkkM9tvYjTn/HApm/3PUDAQqstZAb",
	"RSMiZvUyrsC4YoE7YWyPpMx/bDxYge1NpNLrtwKPcXGM4pyDX8tLQAV2dfWawF0h9GqH5LoMhxC/geZa",
	"jyPqwqvxKRaSOdLY/hmnzshjX92q1MuNIjGuiNycBYvA/1JfVceJMIUywr+5VX3lfO5zjftIlvuCW481",
	"wxE7ZdayJM1B2j/Uq/84oUayws0Vd2Ntv5DzCaUhbmxHZ23va/dT+LapL52j2G8KSeKVBdO1YTiwDu/H",
	"9n7np+cvCL6FjUe7Dlsbr8ezTfZ6W6XQNZX9HMANrsR/AncvO7avp9Y5W4X3Fz/6HzaauaWQ8x6CCl5L",
	"fJ6yBfj76Wc4v0PUPqkqehNfA/xuouJgHF93+3kUaR/6WiUsIxwWkKkCr0SL/seDQYYLUmXs+Dg6jhy8",
	"VOdsX0HfYUtOhDToyUavbZp/4+Mo5r7X0VNrAYtwrrzhZrBH6Ob99f2/AwAA//8Amon+riQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
