// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package postgres

import (
	"context"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    id,
    url,
    format,
    width,
    height,
    full_page,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, 'pending'
)
RETURNING id, url, format, width, height, full_page, status, memory_used_mb, started_at, finished_at, created_at, updated_at
`

type CreateJobParams struct {
	ID       string
	Url      string
	Format   JobFormat
	Width    int32
	Height   int32
	FullPage bool
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.Url,
		arg.Format,
		arg.Width,
		arg.Height,
		arg.FullPage,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Format,
		&i.Width,
		&i.Height,
		&i.FullPage,
		&i.Status,
		&i.MemoryUsedMb,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
