// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type JobFormat string

const (
	JobFormatPng JobFormat = "png"
	JobFormatPdf JobFormat = "pdf"
)

func (e *JobFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobFormat(s)
	case string:
		*e = JobFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for JobFormat: %T", src)
	}
	return nil
}

type NullJobFormat struct {
	JobFormat JobFormat
	Valid     bool // Valid is true if JobFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobFormat) Scan(value interface{}) error {
	if value == nil {
		ns.JobFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobFormat), nil
}

type JobStatus string

const (
	JobStatusPending    JobStatus = "pending"
	JobStatusProcessing JobStatus = "processing"
	JobStatusDone       JobStatus = "done"
	JobStatusFailed     JobStatus = "failed"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus
	Valid     bool // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type Job struct {
	ID           string
	Url          string
	Format       JobFormat
	Width        int32
	Height       int32
	FullPage     bool
	Status       JobStatus
	MemoryUsedMb pgtype.Int4
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
